#!/usr/bin/env node
import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '../..');
const contentRoot = path.join(repoRoot, 'content');
const generatedRoot = path.join(contentRoot, '_generated');
const websiteDataRoot = path.join(repoRoot, 'website/src/data/lens');
const websiteEpisodesDataRoot = path.join(websiteDataRoot, 'episodes');
const websiteDocsRoot = path.join(repoRoot, 'website/src/content/docs');
const evidenceVideosRoot = path.join(contentRoot, 'lens/evidence/videos');
const episodeReadsRoot = path.join(contentRoot, 'lens/episodes');

const authoredExtensions = new Set(['.md', '.mdx', '.yaml', '.yml', '.json', '.jsonl']);
const generatedHeader = 'Generated by ops/scripts/compile-content.mjs. Do not edit by hand.';
const generatedAt = process.env.LENS_GENERATED_AT ?? 'deterministic';

async function walk(dir) {
  const entries = await import('node:fs/promises').then((fs) => fs.readdir(dir, { withFileTypes: true }));
  const files = [];

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    const relPath = path.relative(repoRoot, fullPath);

    if (entry.isDirectory()) {
      if (relPath === 'content/_generated') continue;
      if (relPath === 'content/sources/raw') continue;
      files.push(...await walk(fullPath));
      continue;
    }

    if (entry.isFile() && authoredExtensions.has(path.extname(entry.name))) {
      files.push(fullPath);
    }
  }

  return files;
}

function parseSimpleYaml(text) {
  const data = {};
  const stack = [data];
  const indents = [0];

  for (const line of text.split('\n')) {
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    const nestedMatch = line.match(/^(\s+)([A-Za-z0-9_-]+):\s*(.*)$/);
    const parsed = match
      ? { indent: 0, key: match[1], value: match[2] }
      : nestedMatch
        ? { indent: nestedMatch[1].length, key: nestedMatch[2], value: nestedMatch[3] }
        : null;
    if (!parsed) continue;

    while (parsed.indent < indents[indents.length - 1]) {
      stack.pop();
      indents.pop();
    }

    const parent = stack[stack.length - 1];
    if (parsed.value === '') {
      parent[parsed.key] = {};
      stack.push(parent[parsed.key]);
      indents.push(parsed.indent + 2);
      continue;
    }

    if (parsed.value === '>' || parsed.value === '|') continue;
    parent[parsed.key] = parsed.value.replace(/^["']|["']$/g, '').replace(/^null$/, '');
  }

  return data;
}

function parseFrontmatter(text) {
  if (!text.startsWith('---\n')) return {};
  const end = text.indexOf('\n---', 4);
  if (end === -1) return {};

  const raw = text.slice(4, end).trim();
  const data = {};

  for (const line of raw.split('\n')) {
    const match = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!match) continue;
    const [, key, value] = match;
    if (value === '>' || value === '|') continue;
    data[key] = value.replace(/^["']|["']$/g, '');
  }

  return data;
}

function parseMetadata(text, ext) {
  if (ext === '.yaml' || ext === '.yml') return parseSimpleYaml(text);
  if (ext === '.json') {
    try {
      const parsed = JSON.parse(text);
      return parsed && !Array.isArray(parsed) ? parsed : {};
    } catch {
      return {};
    }
  }

  return parseFrontmatter(text);
}

function inferSection(relPath) {
  const parts = relPath.split(path.sep);
  if (parts[0] !== 'content') return 'unknown';
  return parts.length === 2 ? 'root' : parts[1] ?? 'unknown';
}

function extractClaims(text, relPath) {
  const claims = [];
  const claimPattern = /:::claim\{([^}]*)\}\s*\n([\s\S]*?)\n:::/g;
  let match;

  while ((match = claimPattern.exec(text)) !== null) {
    const attrs = {};
    for (const attr of match[1].matchAll(/([A-Za-z0-9_-]+)="([^"]*)"/g)) {
      attrs[attr[1]] = attr[2];
    }

    claims.push({
      id: attrs.id ?? null,
      evidence: attrs.evidence ?? null,
      source_path: relPath,
      text: match[2].trim().replace(/\s+/g, ' '),
    });
  }

  return claims;
}

function docSlug(filePath) {
  let slug = path.relative(websiteDocsRoot, filePath).replace(/\.mdx?$/, '');
  if (slug.endsWith('/index')) slug = slug.slice(0, -'/index'.length);
  return slug;
}

function docRoute(slug) {
  return slug ? `/${slug}/` : '/';
}

function splitEvidenceRefs(value) {
  return String(value ?? '')
    .split(/[,\s]+/)
    .map((ref) => ref.trim())
    .filter(Boolean);
}

function parseAttrs(value) {
  const attrs = {};
  for (const attr of String(value ?? '').matchAll(/([A-Za-z0-9_-]+)="([^"]*)"/g)) {
    attrs[attr[1]] = attr[2];
  }
  return attrs;
}

function canonicalLensPointId(id) {
  const value = String(id ?? '').trim();
  if (!value) return '';
  return value.startsWith('lens-point:') ? value : `lens-point:${value}`;
}

function lineNumberForIndex(text, index) {
  return text.slice(0, index).split('\n').length;
}

function stripMarkdownForIndex(value) {
  return String(value ?? '')
    .replace(/\[([^\]\n]+)\]\{evidence=(?:"|“)[^"”]+(?:"|”)\}/g, '$1')
    .replace(/\[([^\]\n]+)\]\([^)]+\)/g, '$1')
    .replace(/<[^>]+>/g, '')
    .replace(/[*_`~]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

function firstMarkdownBlockAfter(text, index) {
  const lines = text.slice(index).replace(/^\s+/, '').split('\n');
  const body = [];
  let started = false;

  for (const line of lines) {
    const trimmed = line.trim();
    const isAnchor = /^<(span|a)\b[^>]*\bid="[^"]+"[^>]*>\s*<\/\1>$/.test(trimmed);
    const isComment = /^<!--/.test(trimmed);

    if (!started && (!trimmed || isAnchor || isComment)) {
      continue;
    }

    if (!started) {
      if (/^#{1,6}\s+/.test(trimmed) || /^:::/.test(trimmed)) break;
      started = true;
    }

    if (!trimmed) break;
    body.push(line);
  }

  return body.join('\n').trim();
}

function extractDocEvidenceMarks(text, relPath, slug, title) {
  const marks = [];
  const evidencePattern = /\[([^\]\n]+)\]\{evidence=(?:"|“)([^"”]+)(?:"|”)\}/g;
  let match;

  while ((match = evidencePattern.exec(text)) !== null) {
    marks.push({
      id: `doc-evidence:${slug || 'index'}:${String(marks.length + 1).padStart(4, '0')}`,
      doc_slug: slug,
      doc_path: relPath,
      doc_url: docRoute(slug),
      doc_title: title || slug || 'Index',
      section: slug.startsWith('lens/') ? 'lens' : 'docs',
      line: lineNumberForIndex(text, match.index),
      text: match[1].trim().replace(/\s+/g, ' '),
      refs: splitEvidenceRefs(match[2]),
    });
  }

  return marks;
}

function extractDocLensPoints(text, relPath, slug, title) {
  const points = [];
  const pointPattern = /<!--\s*lens-point\s+([^>]*?)\s*-->/g;
  let match;

  while ((match = pointPattern.exec(text)) !== null) {
    const attrs = parseAttrs(match[1]);
    const anchorId = String(attrs.id ?? '').trim();
    const id = canonicalLensPointId(anchorId);
    const bodyMd = firstMarkdownBlockAfter(text, pointPattern.lastIndex);
    const displayText = stripMarkdownForIndex(bodyMd);

    points.push({
      id,
      anchor_id: anchorId,
      concept: attrs.concept ?? null,
      title: attrs.title ?? null,
      doc_slug: slug,
      doc_path: relPath,
      doc_url: docRoute(slug),
      url: `${docRoute(slug)}#${anchorId}`,
      doc_title: title || slug || 'Index',
      section: slug.startsWith('lens/') ? 'lens' : 'docs',
      line: lineNumberForIndex(text, match.index),
      text: displayText,
      refs: splitEvidenceRefs(attrs.evidence),
    });
  }

  return points;
}

async function collectDocEvidenceMarks() {
  if (!existsSync(websiteDocsRoot)) return [];
  const files = (await walk(websiteDocsRoot)).filter((filePath) => {
    const ext = path.extname(filePath);
    return ext === '.md' || ext === '.mdx';
  });
  const marks = [];

  for (const filePath of files.sort()) {
    const relPath = path.relative(repoRoot, filePath);
    const text = await readFile(filePath, 'utf8');
    const metadata = parseFrontmatter(text);
    const slug = docSlug(filePath);
    marks.push(...extractDocEvidenceMarks(text, relPath, slug, metadata.title));
  }

  return marks;
}

async function collectDocLensPoints() {
  if (!existsSync(websiteDocsRoot)) return [];
  const files = (await walk(websiteDocsRoot)).filter((filePath) => {
    const ext = path.extname(filePath);
    return ext === '.md' || ext === '.mdx';
  });
  const points = [];

  for (const filePath of files.sort()) {
    const relPath = path.relative(repoRoot, filePath);
    const text = await readFile(filePath, 'utf8');
    const metadata = parseFrontmatter(text);
    const slug = docSlug(filePath);
    points.push(...extractDocLensPoints(text, relPath, slug, metadata.title));
  }

  return points;
}

async function listJsonFiles(dir) {
  try {
    const entries = await readdir(dir, { withFileTypes: true });
    return entries
      .filter((entry) => entry.isFile() && entry.name.endsWith('.json'))
      .map((entry) => path.join(dir, entry.name))
      .sort();
  } catch (error) {
    if (error.code === 'ENOENT') return [];
    throw error;
  }
}

function parseJsonl(text) {
  return text
    .split('\n')
    .filter((line) => line.trim())
    .map((line) => JSON.parse(line));
}

function formatDuration(seconds) {
  const value = Number(seconds);
  if (!Number.isFinite(value)) return '';
  const total = Math.max(0, Math.floor(value));
  const hours = Math.floor(total / 3600);
  const minutes = Math.floor((total % 3600) / 60);
  const secs = total % 60;
  if (hours) return `${hours}:${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
  return `${minutes}:${String(secs).padStart(2, '0')}`;
}

function timeRangeStartSeconds(timeRange) {
  const [start] = String(timeRange ?? '').split('-');
  const parts = start.split(':').map((part) => Number(part));
  if (parts.some((part) => !Number.isFinite(part))) return null;
  if (parts.length === 3) return (parts[0] * 3600) + (parts[1] * 60) + parts[2];
  if (parts.length === 2) return (parts[0] * 60) + parts[1];
  return null;
}

function sourceRefSegmentId(ref) {
  const match = String(ref ?? '').match(/#(seg-[0-9]{4})$/);
  return match ? match[1] : null;
}

function compactText(value, maxLength = 220) {
  const text = String(value ?? '').replace(/\s+/g, ' ').trim();
  if (text.length <= maxLength) return text;
  return `${text.slice(0, maxLength - 1).trim()}...`;
}

function dateLabel(source) {
  const date = source.recorded_at || source.published_at;
  if (!date) return 'Undated';
  const precision = source.date_precision ? `, ${source.date_precision} precision` : '';
  return `${date}${precision}`;
}

function refDetail(ref, segmentByRef) {
  const segment = segmentByRef.get(ref);
  if (!segment) {
    return {
      ref,
      segment_id: sourceRefSegmentId(ref),
      time_label: '',
      excerpt: '',
    };
  }

  return {
    ref,
    segment_id: segment.id,
    start: segment.start,
    end: segment.end,
    time_label: formatDuration(segment.start),
    speaker: segment.speaker,
    excerpt: compactText(segment.text),
  };
}

function annotateRefOwner(item, segmentByRef) {
  return {
    ...item,
    refs_detail: (item.refs ?? []).map((ref) => refDetail(ref, segmentByRef)),
  };
}

function lensPointDetail(id, lensPointById) {
  const canonicalId = canonicalLensPointId(id);
  const point = lensPointById.get(canonicalId);
  if (!point) {
    return {
      id: canonicalId,
      valid: false,
      error: 'Missing lens point',
    };
  }

  return {
    id: point.id,
    valid: true,
    concept: point.concept,
    title: point.title,
    doc_title: point.doc_title,
    doc_slug: point.doc_slug,
    url: point.url,
    text: point.text,
    refs: point.refs,
  };
}

function annotateLensPointOwner(item, lensPointById) {
  const lensPoints = item.lens_points ?? [];
  return {
    ...item,
    lens_points: lensPoints,
    lens_points_detail: lensPoints.map((id) => lensPointDetail(id, lensPointById)),
  };
}

function annotateRefs(items, segmentByRef, lensPointById = new Map()) {
  return items.map((item) => annotateLensPointOwner(annotateRefOwner(item, segmentByRef), lensPointById));
}

function sourceRefParts(ref) {
  const video = String(ref ?? '').match(/^video:([^@]+)@transcript:v([0-9]+)#(seg-[0-9]{4})$/);
  if (video) {
    return {
      type: 'video',
      slug: video[1],
      version: Number(video[2]),
      segment_id: video[3],
    };
  }

  return null;
}

function annotateParagraphs(paragraphs, segmentByRef, lensPointById) {
  return (paragraphs ?? []).map((paragraph) => {
    if (typeof paragraph === 'string') {
      return {
        text: paragraph,
        refs: [],
        refs_detail: [],
        marks: [],
        lens_points: [],
        lens_points_detail: [],
      };
    }

    return {
      ...annotateLensPointOwner(annotateRefOwner(paragraph, segmentByRef), lensPointById),
      marks: annotateRefs(paragraph.marks ?? [], segmentByRef, lensPointById),
    };
  });
}

function questionAnswerParagraphs(question) {
  if (Array.isArray(question.answer_paragraphs)) return question.answer_paragraphs;

  const answerText = String(question.answer ?? question.answer_summary ?? '').trim();
  if (!answerText) return [];

  return [{
    text: answerText,
    refs: question.answer_refs ?? question.refs ?? [],
  }];
}

function annotateRead(read, segmentByRef, lensPointById = new Map()) {
  if (!read) return null;
  const opening = read.opening ? annotateLensPointOwner(annotateRefOwner(read.opening, segmentByRef), lensPointById) : null;
  return {
    ...read,
    opening: opening ? {
      ...opening,
      marks: annotateRefs(read.opening?.marks ?? [], segmentByRef, lensPointById),
    } : null,
    beats: (read.beats ?? []).map((beat) => ({
      ...beat,
      start: timeRangeStartSeconds(beat.time_range),
      refs_detail: (beat.refs ?? []).map((ref) => refDetail(ref, segmentByRef)),
      paragraphs: annotateParagraphs(beat.paragraphs ?? (beat.body ? [{ text: beat.body, refs: beat.refs ?? [] }] : []), segmentByRef, lensPointById),
    })),
    questions: (read.questions ?? []).map((question) => ({
      ...question,
      refs_detail: (question.refs ?? []).map((ref) => refDetail(ref, segmentByRef)),
      answer_paragraphs: annotateParagraphs(
        questionAnswerParagraphs(question),
        segmentByRef,
        lensPointById,
      ),
    })),
    source_notes: annotateRefs(read.source_notes ?? [], segmentByRef, lensPointById),
  };
}

async function readEpisodeRead(slug, segmentByRef, lensPointById) {
  const filePath = path.join(episodeReadsRoot, slug, 'read.json');
  if (!existsSync(filePath)) return null;
  return annotateRead(JSON.parse(await readFile(filePath, 'utf8')), segmentByRef, lensPointById);
}

function uniqueRefs(refs) {
  return [...new Set((refs ?? []).filter(Boolean))];
}

function normalizeTerm(term) {
  return String(term ?? '').trim().toLowerCase();
}

function groupedGlossaryTerms(terms, segmentByRef) {
  const groups = new Map();
  for (const term of terms) {
    const key = normalizeTerm(term.term);
    if (!key) continue;
    const current = groups.get(key) ?? {
      term: term.term,
      usages: [],
      refs: [],
    };
    const usage = String(term.definition_or_usage ?? '').trim();
    if (usage && !current.usages.includes(usage)) current.usages.push(usage);
    current.refs.push(...(term.refs ?? []));
    groups.set(key, current);
  }

  return [...groups.values()]
    .map((term) => ({
      ...term,
      refs: uniqueRefs(term.refs),
      refs_detail: uniqueRefs(term.refs).map((ref) => refDetail(ref, segmentByRef)),
    }))
    .sort((a, b) => a.term.localeCompare(b.term));
}

function timestampedUrl(sourceUrl, start) {
  if (!sourceUrl) return null;
  return Number.isFinite(Number(start))
    ? `${sourceUrl}${sourceUrl.includes('?') ? '&' : '?'}t=${Math.floor(Number(start))}s`
    : sourceUrl;
}

function tagSegments(segments, interactions, { slug, sourceUrl } = {}) {
  const tagsBySegment = new Map();
  for (const interaction of interactions) {
    for (const ref of interaction.refs ?? []) {
      const segmentId = sourceRefSegmentId(ref);
      if (!segmentId) continue;
      const tags = tagsBySegment.get(segmentId) ?? new Set();
      if (interaction.kind) tags.add(interaction.kind);
      tagsBySegment.set(segmentId, tags);
    }
  }

  return segments.map((segment) => ({
    ...segment,
    episode_url: slug ? `/episodes/${slug}/` : null,
    transcript_url: slug ? `/episodes/${slug}/transcript/#${segment.id}` : null,
    video_url: timestampedUrl(sourceUrl, segment.start),
    time_label: formatDuration(segment.start),
    tags: [...(tagsBySegment.get(segment.id) ?? [])],
  }));
}

async function buildEpisodeData(semanticFile, lensPointById = new Map()) {
  const aggregate = JSON.parse(await readFile(semanticFile, 'utf8'));
  const sourcePath = path.join(repoRoot, aggregate.generated_from.source_path);
  const transcriptPath = path.join(repoRoot, aggregate.generated_from.transcript_path);
  const source = parseSimpleYaml(await readFile(sourcePath, 'utf8'));
  const transcriptSegments = parseJsonl(await readFile(transcriptPath, 'utf8'));
  const segmentByRef = new Map(transcriptSegments.map((segment) => [segment.source_ref, segment]));
  const interactions = annotateRefs(aggregate.interactions ?? [], segmentByRef);
  const speakerNotes = annotateRefs(aggregate.speaker_notes ?? [], segmentByRef);
  const claims = annotateRefs(aggregate.claims ?? [], segmentByRef);
  const signatureMoments = annotateRefs(aggregate.signature_moments ?? [], segmentByRef);
  const glossaryTerms = groupedGlossaryTerms(aggregate.glossary_terms ?? [], segmentByRef);
  const chronologyNotes = annotateRefs(aggregate.chronology_notes ?? [], segmentByRef);
  const uncertaintyNotes = annotateRefs(aggregate.uncertainty_notes ?? [], segmentByRef);
  const sourceUrl = source.source_url || aggregate.source_url;
  const read = await readEpisodeRead(aggregate.source_slug, segmentByRef, lensPointById);

  const predictions = claims.filter((claim) => claim.claim_type === 'prediction');
  const models = claims.filter((claim) => claim.claim_type === 'model');
  const diagnoses = claims.filter((claim) => claim.claim_type === 'diagnosis');
  const otherClaims = claims.filter((claim) => !['prediction', 'model', 'diagnosis'].includes(claim.claim_type));
  const durationSeconds = transcriptSegments.reduce((max, segment) => Math.max(max, Number(segment.end) || 0), 0);

  return {
    generated_by: generatedHeader,
    generated_at: generatedAt,
    slug: aggregate.source_slug,
    id: aggregate.source_id,
    title: source.title || aggregate.source_title,
    source_url: sourceUrl,
    video_id: source.video_id,
    embed_url: source.video_id ? `https://www.youtube-nocookie.com/embed/${source.video_id}` : null,
    published_at: source.published_at || null,
    recorded_at: source.recorded_at || null,
    date_precision: source.date_precision || aggregate.date_precision || null,
    date_label: dateLabel(source),
    chronology_status: source.chronology_status || 'unknown',
    channel: source.channel ?? null,
    counts: {
      ...aggregate.counts,
      glossary_candidates: aggregate.counts.glossary_terms,
      glossary_terms: glossaryTerms.length,
      transcript_segments: transcriptSegments.length,
      transcript_words: transcriptSegments.reduce((sum, segment) => sum + (Number(segment.word_count) || 0), 0),
      duration_seconds: durationSeconds,
      duration_label: formatDuration(durationSeconds),
    },
    paths: {
      source: aggregate.generated_from.source_path,
      transcript: aggregate.generated_from.transcript_path,
      semantic_bundle: path.relative(repoRoot, semanticFile),
      semantic_passes: aggregate.generated_from.semantic_passes,
      read: read ? path.relative(repoRoot, path.join(episodeReadsRoot, aggregate.source_slug, 'read.json')) : null,
    },
    read,
    transcript: tagSegments(transcriptSegments, aggregate.interactions ?? [], {
      slug: aggregate.source_slug,
      sourceUrl,
    }),
    interactions,
    speaker_notes: speakerNotes,
    claims,
    signature_moments: signatureMoments,
    predictions,
    models,
    diagnoses,
    other_claims: otherClaims,
    glossary_terms: glossaryTerms,
    chronology_notes: chronologyNotes,
    uncertainty_notes: uncertaintyNotes,
  };
}

async function writeEpisodeData(lensPointById = new Map()) {
  await rm(websiteEpisodesDataRoot, { recursive: true, force: true });
  await mkdir(websiteEpisodesDataRoot, { recursive: true });

  const semanticFiles = (await listJsonFiles(evidenceVideosRoot))
    .filter((filePath) => filePath.endsWith('.semantic.json'));
  const episodes = [];

  for (const semanticFile of semanticFiles) {
    const episode = await buildEpisodeData(semanticFile, lensPointById);
    const outputPath = path.join(websiteEpisodesDataRoot, `${episode.slug}.json`);
    await writeFile(outputPath, `${JSON.stringify(episode, null, 2)}\n`);
    episodes.push({
      slug: episode.slug,
      title: episode.read?.title || episode.title,
      source_title: episode.title,
      dek: episode.read?.dek || null,
      source_url: episode.source_url,
      published_at: episode.published_at,
      date_label: episode.date_label,
      read_time: episode.read?.read_time || null,
      counts: episode.counts,
      path: `/episodes/${episode.slug}/`,
      transcript_path: `/episodes/${episode.slug}/transcript/`,
      markdown_path: `/episodes/${episode.slug}.md`,
      data_url: `/data/lens/episodes/${episode.slug}.json`,
      data_path: `website/src/data/lens/episodes/${episode.slug}.json`,
    });
  }

  episodes.sort((a, b) => String(b.published_at ?? '').localeCompare(String(a.published_at ?? '')));
  await writeFile(path.join(websiteEpisodesDataRoot, 'index.json'), `${JSON.stringify({
    generated_by: generatedHeader,
    generated_at: generatedAt,
    episodes,
  }, null, 2)}\n`);

  return episodes;
}

async function readEpisodeDataBySlug(episodes) {
  const data = new Map();
  for (const episode of episodes) {
    const filePath = path.join(repoRoot, episode.data_path);
    data.set(episode.slug, JSON.parse(await readFile(filePath, 'utf8')));
  }
  return data;
}

function refDetailFromEpisodes(ref, episodeBySlug) {
  const parsed = sourceRefParts(ref);
  if (!parsed || parsed.type !== 'video') {
    return {
      ref,
      target_type: 'unknown',
      valid: false,
      error: 'Unsupported or malformed source ref',
    };
  }

  const episode = episodeBySlug.get(parsed.slug);
  if (!episode) {
    return {
      ref,
      target_type: 'video_transcript_segment',
      valid: false,
      video_slug: parsed.slug,
      transcript_version: parsed.version,
      segment_id: parsed.segment_id,
      error: 'Missing episode JSON',
    };
  }

  const segment = (episode.transcript ?? []).find((item) => item.id === parsed.segment_id || item.ref?.endsWith(`#${parsed.segment_id}`));
  if (!segment) {
    return {
      ref,
      target_type: 'video_transcript_segment',
      valid: false,
      video_slug: parsed.slug,
      transcript_version: parsed.version,
      segment_id: parsed.segment_id,
      episode_title: episode.read?.title || episode.title,
      error: 'Missing transcript segment',
    };
  }

  return {
    ref,
    target_type: 'video_transcript_segment',
    valid: true,
    video_slug: parsed.slug,
    transcript_version: parsed.version,
    segment_id: parsed.segment_id,
    episode_title: episode.read?.title || episode.title,
    episode_url: `/episodes/${episode.slug}/`,
    transcript_url: `/episodes/${episode.slug}/transcript/#${segment.id}`,
    video_url: segment.video_url || timestampedUrl(episode.source_url, segment.start),
    published_at: episode.published_at,
    date_label: episode.date_label,
    time_label: segment.time_label || formatDuration(segment.start),
    start: segment.start,
    end: segment.end,
    excerpt: compactText(segment.text),
  };
}

function buildDocEvidenceIndex(docEvidenceMarks, episodeBySlug) {
  const marks = docEvidenceMarks.map((mark) => ({
    ...mark,
    refs_detail: mark.refs.map((ref) => refDetailFromEpisodes(ref, episodeBySlug)),
  }));

  const sourceRefMap = new Map();
  for (const mark of marks) {
    for (const detail of mark.refs_detail) {
      const current = sourceRefMap.get(detail.ref) ?? {
        ...detail,
        docs: [],
      };
      current.docs.push({
        mark_id: mark.id,
        doc_slug: mark.doc_slug,
        doc_path: mark.doc_path,
        doc_url: mark.doc_url,
        doc_title: mark.doc_title,
        line: mark.line,
        text: mark.text,
      });
      sourceRefMap.set(detail.ref, current);
    }
  }

  return {
    doc_evidence_marks: marks,
    source_refs: [...sourceRefMap.values()].sort((a, b) => a.ref.localeCompare(b.ref)),
  };
}

function buildLensPointIndex(docLensPoints, episodeBySlug) {
  return docLensPoints
    .map((point) => ({
      ...point,
      refs_detail: point.refs.map((ref) => refDetailFromEpisodes(ref, episodeBySlug)),
    }))
    .sort((a, b) => a.id.localeCompare(b.id));
}

function collectMarksWithLensPoints(read) {
  const links = [];

  function visitMark(mark, context) {
    for (const id of mark.lens_points ?? []) {
      links.push({
        lens_point_id: canonicalLensPointId(id),
        text: mark.text ?? context.text ?? '',
        refs: mark.refs ?? [],
        source: context,
      });
    }
  }

  function visitParagraph(paragraph, context) {
    for (const mark of paragraph.marks ?? []) {
      visitMark(mark, {
        ...context,
        paragraph_id: paragraph.id ?? null,
        text: paragraph.text,
      });
    }
  }

  if (read?.opening) {
    for (const mark of read.opening.marks ?? []) {
      visitMark(mark, {
        kind: 'opening',
        id: 'opening',
        heading: read.opening.heading ?? 'Core reading',
        text: read.opening.text,
      });
    }
  }

  for (const beat of read?.beats ?? []) {
    for (const paragraph of beat.paragraphs ?? []) {
      visitParagraph(paragraph, {
        kind: 'beat',
        id: beat.id ?? null,
        heading: beat.heading ?? null,
        time_range: beat.time_range ?? null,
      });
    }
  }

  for (const question of read?.questions ?? []) {
    for (const paragraph of question.answer_paragraphs ?? []) {
      visitParagraph(paragraph, {
        kind: 'question',
        id: question.id ?? null,
        heading: question.question ?? null,
      });
    }
  }

  return links;
}

function buildEpisodeLensLinks(episodeBySlug) {
  const links = [];
  for (const episode of episodeBySlug.values()) {
    for (const link of collectMarksWithLensPoints(episode.read)) {
      links.push({
        ...link,
        episode_slug: episode.slug,
        episode_title: episode.read?.title || episode.title,
        episode_url: `/episodes/${episode.slug}/`,
        refs_detail: (link.refs ?? []).map((ref) => refDetailFromEpisodes(ref, episodeBySlug)),
      });
    }
  }

  return links.sort((a, b) => `${a.lens_point_id}:${a.episode_slug}:${a.text}`.localeCompare(`${b.lens_point_id}:${b.episode_slug}:${b.text}`));
}

function addLensPointsToSourceRefs(sourceRefs, lensPoints) {
  const sourceRefMap = new Map(sourceRefs.map((entry) => [entry.ref, {
    ...entry,
    docs: entry.docs ?? [],
    lens_points: entry.lens_points ?? [],
  }]));

  for (const point of lensPoints) {
    for (const detail of point.refs_detail ?? []) {
      const current = sourceRefMap.get(detail.ref) ?? {
        ...detail,
        docs: [],
        lens_points: [],
      };
      current.lens_points.push({
        id: point.id,
        concept: point.concept,
        doc_slug: point.doc_slug,
        doc_url: point.doc_url,
        url: point.url,
        doc_title: point.doc_title,
        line: point.line,
        text: point.text,
      });
      sourceRefMap.set(detail.ref, current);
    }
  }

  return [...sourceRefMap.values()].sort((a, b) => a.ref.localeCompare(b.ref));
}

async function main() {
  if (!existsSync(contentRoot)) {
    throw new Error(`Missing content root: ${contentRoot}`);
  }

  await mkdir(generatedRoot, { recursive: true });
  await mkdir(websiteDataRoot, { recursive: true });

  const files = await walk(contentRoot);
  const manifestFiles = [];
  const claims = [];

  for (const filePath of files.sort()) {
    const relPath = path.relative(repoRoot, filePath);
    const text = await readFile(filePath, 'utf8');
    const metadata = parseMetadata(text, path.extname(filePath));

    manifestFiles.push({
      path: relPath,
      section: inferSection(relPath),
      id: metadata.id ?? null,
      title: metadata.title ?? null,
      kind: metadata.kind ?? metadata.type ?? null,
    });

    if (path.extname(filePath) === '.md' || path.extname(filePath) === '.mdx') {
      claims.push(...extractClaims(text, relPath));
    }
  }

  const manifest = {
    generated_by: generatedHeader,
    generated_at: generatedAt,
    counts: {
      files: manifestFiles.length,
      claims: claims.length,
    },
    files: manifestFiles,
  };

  const manifestJson = `${JSON.stringify(manifest, null, 2)}\n`;

  await writeFile(path.join(generatedRoot, 'manifest.json'), manifestJson);
  await writeFile(path.join(websiteDataRoot, 'manifest.json'), manifestJson);

  const docsIndex = [
    '---',
    'title: Content Index',
    'description: Generated index of Jiang Lens content.',
    '---',
    '',
    '# Content Index',
    '',
    `_${generatedHeader}_`,
    '',
    `Generated at: \`${manifest.generated_at}\``,
    '',
    `Indexed files: **${manifest.counts.files}**`,
    '',
    `Claim blocks: **${manifest.counts.claims}**`,
    '',
    '## Files',
    '',
    ...manifest.files.map((file) => `- \`${file.path}\`${file.title ? ` - ${file.title}` : ''}`),
    '',
  ].join('\n');

  await writeFile(path.join(generatedRoot, 'content-index.md'), docsIndex);
  const docLensPoints = await collectDocLensPoints();
  const lensPointById = new Map(docLensPoints.map((point) => [point.id, point]));
  const episodes = await writeEpisodeData(lensPointById);
  const episodeBySlug = await readEpisodeDataBySlug(episodes);
  const docEvidence = buildDocEvidenceIndex(await collectDocEvidenceMarks(), episodeBySlug);
  const lensPoints = buildLensPointIndex(docLensPoints, episodeBySlug);
  const episodeLensLinks = buildEpisodeLensLinks(episodeBySlug);
  const sourceRefs = addLensPointsToSourceRefs(docEvidence.source_refs, lensPoints);

  const linkIndex = {
    generated_by: generatedHeader,
    generated_at: generatedAt,
    counts: {
      claims: claims.length,
      doc_evidence_marks: docEvidence.doc_evidence_marks.length,
      doc_evidence_refs: docEvidence.doc_evidence_marks.reduce((sum, mark) => sum + mark.refs.length, 0),
      unique_source_refs: sourceRefs.length,
      lens_points: lensPoints.length,
      episode_lens_links: episodeLensLinks.length,
    },
    claims,
    doc_evidence_marks: docEvidence.doc_evidence_marks,
    lens_points: lensPoints,
    episode_lens_links: episodeLensLinks,
    source_refs: sourceRefs,
  };

  const linkIndexJson = `${JSON.stringify(linkIndex, null, 2)}\n`;
  await writeFile(path.join(generatedRoot, 'link-index.json'), linkIndexJson);
  await writeFile(path.join(websiteDataRoot, 'link-index.json'), linkIndexJson);

  console.log(`Compiled ${manifest.counts.files} content files, ${manifest.counts.claims} claim blocks, ${linkIndex.counts.doc_evidence_marks} doc evidence marks, ${linkIndex.counts.lens_points} lens points, and ${episodes.length} episode data files.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
